### ISSUE TITLE
adobe 설치 영문요

### ISSUE THREAD

**Issue by byeun-seo-eun** [yamoo9/PSD2HTML-CSS#7]
샘 adobe 영문판 설치하려 어떻게 해야해요^^

좋은하루 보내세요~~

**Comment by yamoo9** [comment]
인터넷에 이미 인터페이스 한글 ↔ 영문 변환 관련 글이 있어 링크 남깁니다. ^^
참고하시고 변경해보세요~ http://goodperson.tistory.com/1270

**Comment by yamoo9** [comment]
인터페이스 한글 ↔ 영문 변환 관련 글이 있어 링크 남깁니다. ^^
참고하시고 변경해보세요~ 

- http://blog.naver.com/etocat/220329079400
- http://goodperson.tistory.com/1270

설치 언어 환경설정 변경에 관한 정보는 아래 링크를 참고하세요
- http://blog.naver.com/skysong0401/220129069692

**Comment by yamoo9** [comment]
인터페이스 한글 ↔ 영문 변환 관련 글이 있어 링크 남깁니다. ^^
참고하시고 변경해보세요~ 

- http://blog.naver.com/etocat/220329079400
- http://goodperson.tistory.com/1270

설치 언어 환경설정 변경에 관한 정보는 아래 링크를 참고하세요
- http://blog.naver.com/skysong0401/220129069692
