### ISSUE TITLE
샘 질문있어요

### ISSUE THREAD

**Issue by byeun-seo-eun** [yamoo9/PSD2HTML-CSS#8]
연습한건데  모바일에서 테스트 하면 메뉴 클릭해을때 
nav 부분으로 화면이 내려가요 
이유가 뭔지.
궁금해서 질문드려요~

즐건주말 보내세요^^

**Comment by yamoo9** [comment]
원인은 `.home a` 요소의 `href` 속성에 따른 **브라우저 기본 동작**을 제어하지 못했기 때문입니다. :-) 
코드를 아래와 같이 고쳐보면 문제가 해결될 겁니다. 다만... 현재 작성하신 코드의 **접근성은 Zero**입니다.
왜 접근성 문제가 되는가는 수업하기 전이나, 쉬는 시간에 물어봐주세요 ^^

```js
$(function(){
  $nav = $('nav');
  $('.home a').on('click', function(e){
    e.preventDefault();
    $nav.slideToggle();
 });
});
```

**Comment by byeun-seo-eun** [comment]
샘 감사합니다.^^
