### ISSUE TITLE
이미지 에셋으로 SVG포맷을 생성할 때 기본여백을 포함할 수 있는 방법이 있을까요?

### ISSUE THREAD

**Issue by des1gner** [yamoo9/PSD2HTML-CSS#9]
제너레이터 기능이 편리해서 좋은대요.. 
수업때도 얘기가 나왔듯이 아이콘의 경우 32*32 또는 16*16 과 같이 일정한 크기로 제작이 되어야지
UI 요소로 사용할 때 일정한 위치에 공통적으로 반영이 될텐데 투명여백을 제외한 영역으로 
잘라지다보니 약간 불편한 감이 있습니다. 
현재는 SVG로 내보낸 후 일러스트에서 불러들여 도큐먼트사이즈를 변경후 사용하고 있습니다.
일정한 사이즈로 여백을 포함해서 내보내기는 어렵지 않나 싶은데 
이보다 좋은 방법이 있을지 여쭤보고싶습니다.

**Comment by yamoo9** [comment]
해결 방법은 간단합니다. :-)
아래 그림처럼 투명영역을 레이어 마스크로 만들어주면 
투명영역까지 포함되어 아이콘을 잘라냅니다.

![Photoshop Image Asset](https://raw.githubusercontent.com/yamoo9/PSD2HTML-CSS/master/__assets__/ps-asset-transparent-area.jpg)
